### ISSUE TITLE
Using 'name' as variable name produces error

### ISSUE THREAD

**Issue by newhouse** [stalniy/bdd-lazy-var#142]
Something like this:
```js
describe('a test', function ()  {
  def('name', () => 'Some Name')

  it('works', function () {
    expect($.name).to.eql('Some Name')
  })
})
```

Results in an error like this:
```sh
Error: Cannot create lazy variable "name" as variable with the same name exists on the provided context
    at defineGetter (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:768:13)
    at Object.onDefineVariable (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:784:7)
    at runHook (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:471:22)
    at def (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:367:9)
    at Suite.<anonymous> (/Path/to/my/project/test/server/lib/filestore.test.js:2:3)
    at SuiteTracker.execute (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:553:19)
    at SuiteTracker.trackSuite (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:538:12)
    at Suite.defineSuite (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:529:19)
    at Object.create (/Path/to/my/project/node_modules/mocha/lib/interfaces/common.js:148:19)
    at Object.only (/Path/to/my/project/node_modules/mocha/lib/interfaces/common.js:106:21)
    at context.describe.only (/Path/to/my/project/node_modules/mocha/lib/interfaces/bdd.js:69:27)
    at Function.detectSuite [as only] (/Path/to/my/project/node_modules/bdd-lazy-var/getter.js:524:25)
    at Object.<anonymous> (/Path/to/my/project/test/server/lib/filestore.test.js:1:85)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/Path/to/my/project/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Path/to/my/project/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (/Path/to/my/project/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/Path/to/my/project/node_modules/mocha/lib/esm-utils.js:55:34)
    at singleRun (/Path/to/my/project/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Path/to/my/project/node_modules/mocha/lib/cli/run.js:362:5)
```

I've not reproduced in a sterile environment, but I have grep'd my codebase and there is nowhere else that I `def('name', ...)`...and it would/should only matter if I do it in the same `describe` or `context` block anyways...

**Comment by newhouse** [comment]
Oh, also, I should mention that I'm using this trick to keep my code lint-free:
https://github.com/stalniy/bdd-lazy-var/issues/56#issuecomment-639248242

And if I log the value of `$.name`, it appears to be `'get'`...so this is probably the reason. Not sure if this is a bug and/or something I can do anything about?

**Comment by stalniy** [comment]
I've been quiet for some time 😄 but today I pushed a new version of lazy vars with typescript support. It's unfinished, I mean it's from feature point of view is done but requires some cleanup and tools update (build, eslint, etc). Write simple adapters for popular frameworks and then will release a new version

Please take a look here -> https://github.com/stalniy/bdd-lazy-var/blob/49325c56388eff5f7c550850d1788e5ba33b05e8/spec/interface_examples.ts#L29

Feel free to provide feedback if you are still using bdd-lazy-var.

This bug won't be relevant anymore, so closing it as won't fix. Just use a different name for that variable, like `userName`
