### ISSUE TITLE
Reference to parent subject is deleted prematurely

### ISSUE THREAD

**Issue by Visya** [stalniy/bdd-lazy-var#16]
Looks like the reference to parent subject is deleted prematurely.
```
describe('Parent', function() {
  subject(function() {
    return {
      getName: function() {
        return 'Nick';
      },
      doSmth: function() {
      }
    };
  });

  describe('Name', function() {
    subject(function() {
      subject().doSmth();

      return subject().getName();
    });

    it('is retrieved', function() {
      expect(subject()).to.equal('Nick');
    });
  });
});
```

This example fails with
```
1) Parent Name is retrieved:
   Error: Unknown parent variable "subject".
    at Context.<anonymous> (.\test.js:21:16)
    at Context.<anonymous> (.\test.js:25:16)
```

However, if I comment out `subject().doSmth();` line, the test passes.

**Comment by stalniy** [comment]
Thanks for posting this. Fixed by 9f71d451d1159f01c4a1fe93b8292f106389853b . Available in 1.1.9
