### ISSUE TITLE
Is it expected that calling get for a value which is not defined throws an error ?

### ISSUE THREAD

**Issue by iain-b** [stalniy/bdd-lazy-var#31]
More of a question but I'm getting an error trying calling `get` for a value which is undefined (has no corresponding `def` rather than is set to undefined). Is this expected ? If so could there be a better error message like `The value 'foo' was not defined` or similar. 

Currently, I'm getting an error as follows, it doesn't really give me much to go on:
```‣
TypeError: Cannot read property 'evaluate' of undefined
    at Metadata.getVar (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:206:45)
    at Variable.value (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:304:42)
    at Function.evaluate (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:275:25)
    at get$$1 (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:356:23)
    at assets/unit.js:56381:18
    at VariableMetadata.evaluate (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:159:44)
    at Metadata.getVar (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:206:45)
    at Variable.value (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:304:42)
    at Function.evaluate (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:275:25)
    at get$$1 (eval at Array.concat.module.exports (assets/unit.js:23649:9), <anonymous>:356:23)```

**Comment by stalniy** [comment]
Hi thank you for the issues!

I will try to check it soon
