### ISSUE TITLE
Cannot read property 'getEnv' of undefined

### ISSUE THREAD

**Issue by pmoons** [stalniy/bdd-lazy-var#97]
On version `2.5.4` of `bdd-lazy-var`, I am receiving the error:

```
    > 1 | import "bdd-lazy-var/global";
        | ^

      at Object.createUi (node_modules/bdd-lazy-var/global.js:648:44)
      at node_modules/bdd-lazy-var/global.js:782:37
      at node_modules/bdd-lazy-var/global.js:3:83
      at Object.<anonymous> (node_modules/bdd-lazy-var/global.js:6:2)
      at Object.<anonymous> (src/setupTests.js:1:1)
```

This is in `src/setupTests` file, which (it being a `create-react-app` app), is the file specified as the jest argument in `setupFilesAfterEnv`.

create-react-app v4.0.0

---

My guess is it has to do something with this [line of code](https://github.com/stalniy/bdd-lazy-var/blob/5b528543d8ef0c36bc9e3d6bf56b46cda5de56f1/lib/interface/jasmine.js#L42), as it seems the `interface/jest` file just points to the `interface/jasmine` file. 

Any ideas what I'm doing wrong here?

**Comment by stalniy** [comment]
Jest is a rewritten version of jasmine :) that’s why they have completely behavior. 

The actual error is not clear for me. Is there any message?

**Comment by stalniy** [comment]
Ah I see. For a long time jest defined global jasmine variable maybe it was removed finally))

**Comment by stalniy** [comment]
what is your version of jest?

**Comment by stalniy** [comment]
just checked on jest@26.5.3 everything works fine. all tests in the repo pass. Also released a patch version with updates to the dependencies

**Comment by pmoons** [comment]
I believe my version of create-react-app is using 26.6.0

https://github.com/facebook/create-react-app/blob/master/package.json#L33

**Comment by stalniy** [comment]
you can actually clone this repo, try to update jest and run `npm run test.jest-ui` if it fails then I'll investigate. Will be able to look at it tomorrow only

**Comment by pmoons** [comment]
So, cloning this repo, updating jest to 26.6.0, running `npm install` and then `npm run test .jest-ui` results in this error:

```
⌂116% [peter:~/Workspaces/bdd-lazy-var] master(+297/-271) 48d0h57m34s ± npm run test.jest-ui

> bdd-lazy-var@2.5.4 test.jest-ui /Users/peter/Workspaces/bdd-lazy-var
> SRC_FILE=index.js jest --findRelatedTests spec/interface_spec.js

 FAIL  spec/interface_spec.js
  ● Test suite failed to run

    Cannot find module '../index.js' from 'tools/jest.setup.js'

      2 |
      3 | require('../spec/config');
    > 4 | require(`../${uiFile}`);
        | ^
      5 | require('../spec/interface_examples');
      6 | require('../spec/default_suite_tracking_examples');
      7 | require('../spec/shared_behavior_spec');

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (tools/jest.setup.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.044 s
Ran all test suites related to files matching /spec\/interface_spec.js/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bdd-lazy-var@2.5.4 test.jest-ui: `SRC_FILE=index.js jest --findRelatedTests spec/interface_spec.js`
npm ERR! Exit status 1
```

Not the same one I was experiencing with create-react-app. Am I missing something?

**Comment by stalniy** [comment]
I guess, you also need to use `npm run build`, tests are run on bundled files

**Comment by pmoons** [comment]
Hmm, updating jest to 26.6.0 and running tests on this repo work fine, so it must be a problem on my end. I'll close this issue, and post here if I figure out what the problem is.

**Comment by pmoons** [comment]
Here is a bare-bones repo of the problem at hand:
https://github.com/pmoons/test-bdd-lazy-var

Performing `yarn test` in the repo produces the same error I mentioned here.

All I did was:
- `npx create-react-app test-bdd-lazy-var`
- `cd test-bdd-lazy-var`
- `yarn add -D bdd-lazy-var`
- Add `import 'bdd-lazy-var/global` to `src/setupTests`

Not sure what is going on, but any ideas would be appreciated.

**Comment by stalniy** [comment]
Ok. Thanks. I’ll check it

**Comment by stalniy** [comment]
I think the issue is that you are trying to import it too early. At that stage `global.jasmine` doesn't exist. I think CRA puts `src/setupTests` into https://jestjs.io/docs/en/configuration#setupfiles-array but bdd-lazy-var needs to be executed in https://jestjs.io/docs/en/configuration#setupfilesafterenv-array

**Comment by stalniy** [comment]
just try to do `console.log(global.beforeAll)` if it's undefined, than my assumption is correct

**Comment by stalniy** [comment]
Anyway, ideally I need to add a check with the proper error message, so users are no confused. That's why I reopen this issue

**Comment by pmoons** [comment]
I think CRA does put it in `setupFilesAfterEnv` array, judging from this example: https://create-react-app.dev/docs/running-tests/#srcsetuptestsjs

Just weird that downgrading CRA to its previous release, 3.4.0, doesn't cause the issue.

**Comment by halilb** [comment]
> I think CRA does put it in `setupFilesAfterEnv` array, judging from this example: https://create-react-app.dev/docs/running-tests/#srcsetuptestsjs
> 
> Just weird that downgrading CRA to its previous release, 3.4.0, doesn't cause the issue.

I'm having the same problem, and the only thing that worked for me was downgrading the CRA as well. @stalniy Any ideas how to fix it with the new CRA version?

**Comment by pete-mann** [comment]
Having the same issue. It was caused when updating react-scripts from 3 to 4, `global.jasmine` is undefined in react-scripts 4.

**Comment by stalniy** [comment]
I’ll check today whether access to rootSuite really necessary (qqq jasmine

**Comment by stalniy** [comment]
I finally understood why it throws. The issue is in new `jest-circus` package. This is a test runner that is going to replace jest starting from v27. And it looks like new CRA uses `jest-circus` in jest.config. This is a completely new test runner which does not depend on jasmine. That's why it throws.

Looks like this is a completely new feature for bdd-lazy-var!

**Comment by stalniy** [comment]
![Screenshot from 2021-02-04 10-45-00](https://user-images.githubusercontent.com/1159966/106867283-14a00d00-66d6-11eb-8294-3763a55718f3.png)

This is a screenshot of package.json after `react-scripts eject` command in the project described in [this comment](https://github.com/stalniy/bdd-lazy-var/issues/97#issuecomment-717665083)

**Comment by stalniy** [comment]
There is very little information about jest-circus and its internals, so it will take some time to create/adapt integration for it

**Comment by stalniy** [comment]
So, the workaround is too switch back `jest-jasmine2` runner, however I don't know whether it's possible to change jest config without ejection.

**Comment by stalniy** [comment]
I have some thoughts on how to improves typescript integration and this may change how variables are created and integrated with testing framework.  Something like this

```ts
import { scope } from 'bdd-lazy-var'

describe('suite', () => {
  const $ = scope()
     .def('num', 5)
     .def('user', () => new User())

  it('tests', () => {
     expect($.user.age).toEqual($.num);
  })
})
```

**Comment by stalniy** [comment]
However the issue with this approach is that for every nested describe we need a separate variable but we can't use the same name every time. So, the only way to solve this in typesafe way is to use 2 variable names, one common like `$` and another one common `$parent`:

```js
import { lazy } from 'bdd-lazy-var'

describe('suite', () => {
  const $ = lazy()
     .variable('num', 5)
     .variable('user', () => new User({ age: $.num }));
  const $parentVars = $;

  it('tests', () => {
     expect($.user.age).toEqual($.num);
  })
 
  describe('nested suite', () => {
    const $ = lazy.extend($parentVars)
       .variable('num', 10);

    it('tests', () => {
       expect($.user.age).toEqual($.num);
    })
  })
})
```

Also it requires to disable eslint no-shadow rule to allow use the same variable name in nested `desribe`s. 

I can make the API a bit simpler by automatically tracking child/parent relationship but to keep variables safe, we still need to define a separate type:

```ts
describe('suite', () => {
  const $ = lazy()
     .variable('num', 5)
     .variable('user', () => new User({ age: $.num }));
  type ParentVars = typeof $; // <----- we need a type reference

  it('tests', () => {
     expect($.user.age).toEqual($.num);
  })
 
  describe('nested suite', () => {
    const $ = lazy<ParentVars>() // automatically inherits parent variables
       .variable('num', 10);

    it('tests', () => {
       expect($.user.age).toEqual($.num);
    })
  })
})
```

The 2nd approach complicates implementation and doesn't actually bring simplicity in comparison to the 1st one (only for js users).

**Comment by pmoons** [comment]
Thanks for nailing down what was causing this. I'm sure a lot of people will appreciate that workaround, and hopefully `jest-circus` compatibility in the near term.

As for improving typescript support, I like first the interface of the first example `lazy.extends` over the second, but not a fan of having to disable eslint `no-shadow` rule in either case.

**Comment by stalniy** [comment]
Would it be better to have a convention like `$`, `$1`, `$2`, ... where number after $ means a nesting level. Usually it shouldn’t go deeper $2.

```ts
import { lazy } from 'bdd-lazy-var'

describe('suite', () => {
  const $ = lazy()
     .variable('num', 5)
     .variable('user', () => new User({ age: $.num }));

  it('tests', () => {
     expect($.user.age).toEqual($.num);
  })
 
  describe('nested suite', () => {
    const $1 = lazy.extend($)
       .variable('num', 10);

    it('tests', () => {
       expect($1.user.age).toEqual($1.num);
    })
  })
})
```

 In this case, no need to create $parentVars variable and no need to disable or add exceptions to no-shadow eslint rule. However, this still may be an option for some people. 

As an alternative, for js users and those who are ok with weak typing in tests, we can do this (what is almost identical to the current behavior):

```ts
import { lazy } from 'bdd-lazy-var'

let $: Record<string, any>;
describe('suite', () => {
  $ = lazy()
     .variable('num', 5)
     .variable('user', () => new User({ age: $.num }));

  it('tests', () => {
     expect($.user.age).toEqual($.num);
  })
 
  describe('nested suite', () => {
    $ = lazy.extend($)
       .variable('num', 10);

    it('tests', () => {
       expect($.user.age).toEqual($.num);
    })
  })
})
```

I also will leave `lazy().def(...)` just for easier migration.

**Comment by ahmadabdul3** [comment]
Just ran into this issue as well, then I realized who the OP was and wanted to say hi - what's up @pmoons!

**Comment by Aror** [comment]
I'm not sure ejecting or redefining variables in every describe block is going to work for everyone. I have 100s of tests that rely on bdd-lazy-var. Any updates on this?

**Comment by stalniy** [comment]
No updates. What interface do you use, bad-lazy-var/global?

**Comment by Aror** [comment]
Yeah, we use `def` from bdd-lazy-var/global @stalniy

**Comment by GaoYu620** [comment]
@stalniy Just ran into this issue and we use `bdd-lazy-var/getter` and update the jest version to 27.0.5 in our codebase, most of our test cases are failed, would like to know do you have any plans within two months to provide a fix for this issue? 
![image](https://user-images.githubusercontent.com/41660177/123729111-08a42a00-d8c7-11eb-9d87-88f29ef76d2c.png)

**Comment by stalniy** [comment]
Probably no, but I think that I will fix it till the end of this year. Just not a priority for me right now, sorry guys

**Comment by rinslow** [comment]
Kinda hard to contribute to this amazing and important project when the build fails :(

**Comment by ignatospadov** [comment]
Hey @stalniy could you please give a quick update on the status of making `bdd-lazy-var` work with `jest-circus`?

**Comment by stalniy** [comment]
No any updates guys, sorry guys.

**Comment by stalniy** [comment]
it seems that [jest-circus](https://github.com/facebook/jest/blob/main/packages/jest-circus/src/state.ts#L44) exports access to its state, which potentially means I can add integration for it without changing the public interface.

**Comment by stalniy** [comment]
jest-circus exposes access to its state, so I can add support for it in 2.x  version

**Comment by stalniy** [comment]
However, I still think that bdd-lazy-var need to go in the direction of being more independent from testing framework integration in v3. This will enable this interface:

```ts
// it's a working prototype

import { lazy, clearUsedScopes } from 'bdd-lazy-var';

afterEach(() => {
  clearUsedScopes();
})

describe('suite', () => {
  let i = 0;
  const $ = lazy(b => b
    .variable('num', () => i++)
    .variable('p', 1)
    .variable('user', ({ num }) => ({ age: num }))
  )

  it('tests 1', () => {
     expect($.user.age).toEqual($.num);
  })

  it('tests 2', () => {
    expect($.user.age).toEqual($.num);
  })

  describe('nested suite', () => {
    const $1 = lazy(b => b.extends($)
      .variable('num', ({ num, p }) => p + num + 1)
    );

    it('tests', () => {
       expect($1.user.age).toEqual($1.num);
    })
  })
})
```

In case we want to get access to active scope in parent `before/after` callbacks, this interface will add few restrictions:
1. it won't be possible to access active scope in `before/after` callbacks before `lazy` vars definition
    ```ts
     import { $active } from 'bdd-lazy-var/jasmine-globals';

     describe('test', () => {
       beforeEach(() => console.log($active.num)) // fails with error
       beforeEach(() => console.log($.num)) // works OK

       const $ = lazy(b => b
         .variable('num', () => 5)
         .variable('user', ({ num }) => ({ age: num }))
       )

       beforeEach(() => console.log($active.num)) // works OK
       beforeEach(() => console.log($.num)) // works OK
     })
    ```
2. in `afterAll` callbacks, if lazy vars are accessed they will be re-created. 
3. Only 1 `lazy` block should be used inside one `describe` (in 99.9% this how things are done by definition but anyway)

That means, ideally we should structure our tests in such a way that we never need run side-effects based on`$active` scope. There is additional benefit of not using it -

**Comment by MrDOS** [comment]
For anyone running into this error after upgrading Jest, you're seeing this because Jest 27 [changed its defaults](](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults)) to use [the Circus test runner](https://www.npmjs.com/package/jest-circus). You can keep using bdd-lazy-var by explicitly using the older jest-jasmine2 runner. Bring in that package as a dependency:

```
npm i -D jest-jasmine
```

or

```
yarn add -D jest-jasmine2
```

Then [configure Jest to use it as the runner](https://jestjs.io/docs/configuration#testrunner-string). In your `jest.config.js`:

```js
module.exports = {
	// ...
	testRunner: "jest-jasmine2",
	// ...
};
```

**Comment by stalniy** [comment]
I've been quiet for some time 😄 but today I pushed a new version of lazy vars with typescript support. It's unfinished, I mean it's from feature point of view is done but requires some cleanup and tools update (build, eslint, etc). Write simple adapters for popular frameworks and then will release a new version

Those who are interested please take a look here -> https://github.com/stalniy/bdd-lazy-var/blob/49325c56388eff5f7c550850d1788e5ba33b05e8/spec/interface_examples.ts#L29

Obviously there will be breaking changes but I assume not much in terms of behavior
